### ISSUE TITLE
No filters loaded for argo layer

### ISSUE THREAD

**Issue by jkburges** [aodn/aodn-portal#1631]
The message "Filtering of this collection is not available at this time." appears.  

**Steps to reproduce**
1. On portal branch `filters_from_geoserver` and configured to use geoserver filters, running against a geoserver in PO box
2. Add collection "IMOS - Argo Australia Profiles"

**What happens**
The message "Filtering of this collection is not available at this time." appears, with no filters showing.

The following error in the portal log:

```log4j
ERROR 2015-03-18 10:27:47,662 [http-8080-6 ] au.org.emii.portal.wms.WmsServer (User: anon.) - Unable to parse filters for server 'http://geoserver-123.aodn.org.au/geoserver/wms', layer 'imos:argo_profile_download_data'
java.io.IOException: Server returned HTTP response code: 500 for URL: http://geoserver-123.aodn.org.au/geoserver/wms?request=enabledFilters&service=layerFilters&version=1.0.0&workspace=imos&layer=argo_profile_download_data
```

The following error in geoserver log:

```log4j
18 Mar 10:27:49 ERROR [geoserver.ows] - 
java.lang.RuntimeException: java.lang.NullPointerException
        at au.org.emii.geoserver.extensions.filters.LayerFiltersService.enabledFilters(LayerFiltersService.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<snip>
Caused by: java.lang.NullPointerException
        at org.geoserver.config.GeoServerDataDirectory.get(GeoServerDataDirectory.java:1037)
        at au.org.emii.geoserver.extensions.filters.layer.data.DataDirectory.getLayerDataDirectoryPath(DataDirectory.java:36)
        at au.org.emii.geoserver.extensions.filters.LayerFiltersService.getLayerDataDirectoryPath(LayerFiltersService.java:122)
        at au.org.emii.geoserver.extensions.filters.LayerFiltersService.getEnabledFiltersDocument(LayerFiltersService.java:89)
        at au.org.emii.geoserver.extensions.filters.LayerFiltersService.enabledFilters(LayerFiltersService.java:63)
```

**What should happen**
The argo collection loads *along with* the filters configured in geoserver.

Note that this happens for "argo" layers but not for "IMOS - AATAMS Facility Satellite Relay Tagging Program - Near real-time data".  Haven't checked any other collections.

**Comment by danfruehauf** [comment]
I've witnessed that before and I thought it was actually fixed by @julian1 's recent work.

Might be related to argo having a virtual layer, @julian1 probably knows more.

**Comment by jkburges** [comment]
This is an issue with a geonetwork/geoserver configuration mismatch with my development setup.  Specifically in this case, I was hitting production geonetwork, but using the master branch of geoserver.  The prod geonetwork is referring to an argo layer ("argo_profile_download_data") which exists in the production branch of geoserver but not in master.
