### ISSUE TITLE
Incorrect pop-up on step 3 when downloading ncWMS

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2018]
App version: 4.15.3
            Build date: Tue Sep 29 12:17:44 AEST 2015
            Build number: 20
            Git ref: f5e30b566e43440ba6dc8c5632ae7ee7392ad2b6

This is the issue I saw yesterday when there were weird things going on with systest and prod.

Steps to reproduce:

Select any ncwms collection today I used ACORN Rottnest. Subset to one day. Proceed to step 3 and select download as netcdf.

What should happen:

Get a pop-up indicating where to see statues page and letting me know job has started and could take any amount of time. Then get emails regarding the downloading.

What does happen:

See this pop-up:

![wrong popup](https://cloud.githubusercontent.com/assets/2906602/10294943/f6e81f78-6c08-11e5-8040-10abe018d865.jpg)

But then still get email for requested job and also email for success of job.

**Comment by pmbohm** [comment]
Tried this on edge:
```
2015-10-07 16:04:03,748 ERROR [http-bio-8080-exec-390] [] grails.app.controllers.au.org.emii.portal.AsyncDownloadController  - Problem registering new aggregator job with type 'gogoduck' and parameters: '[jobParameters:{"layerName":"acorn_hourly_avg_rot_qc_timeseries_url","emailAddress":"pmbohm@gmail.com","geoserver":"http://geoserver-123.aodn.org.au/geoserver","subsetDescriptor":{"temporalExtent":{"start":"2010-02-23T06:30:00.000Z","end":"2010-03-11T23:30:00.000Z"},"spatialExtent":{"north":90,"south":-90,"east":180,"west":-180}}}, _dc:1444194206795, controller:asyncDownload]'
java.lang.RuntimeException: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error converting Bean with class net.sf.json.JSONNull
	at java.lang.String.valueOf(String.java:2847)
	at java.lang.StringBuilder.append(StringBuilder.java:128)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:493)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:427)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:359)
	at au.org.emii.portal.AsyncDownloadService.registerJob(AsyncDownloadService.groovy:19)
	at au.org.emii.portal.AsyncDownloadController$_closure1.doCall(AsyncDownloadController.groovy:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error converting Bean with class net.sf.json.JSONNull
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.convertAnother(JSON.java:162)
	at grails.converters.JSON.value(JSON.java:202)
	at grails.converters.JSON.render(JSON.java:134)
	... 10 more
Caused by: java.lang.reflect.InvocationTargetException
	... 14 more
Caused by: net.sf.json.JSONException: Object is null
	at net.sf.json.JSONNull.isEmpty(JSONNull.java:69)
	... 14 more
```

**Comment by pmbohm** [comment]
HHMMMmmmmm
##### Using http://gogoduck.aodn.org.au/go-go-duck with Intellij
Wanting a JSON response (above comment) and getting XML
```
ERROR 2015-10-08 10:49:05,861 [http-bio-8080-exec-3] grails.app.utils.au.org.emii.portal.HttpUtils$Status - Problem registering new aggregator job with type 'gogoduck' and parameters: '[jobParameters:{"layerName":"acorn_hourly_avg_rot_qc_timeseries_url","emailAddress":"pmbohm@gmail.com","geoserver":"http://geoserver-123.aodn.org.au/geoserver","subsetDescriptor":{"temporalExtent":{"start":"2014-06-06T01:30:00.000Z","end":"2014-06-06T02:30:00.000Z"},"spatialExtent":{"north":90,"south":-90,"east":180,"west":-180}}}, _dc:1444261744991, controller:asyncDownload]'
groovyx.net.http.ResponseParseException: Found
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:486)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:506)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:425)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:357)
	at au.org.emii.portal.AsyncDownloadService.registerJob(AsyncDownloadService.groovy:19)
	at au.org.emii.portal.AsyncDownloadController$_closure1.doCall(AsyncDownloadController.groovy:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is '<' with an int value of 60
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^
	at groovyx.net.http.ParserRegistry.parseJSON(ParserRegistry.java:280)
	at groovyx.net.http.HTTPBuilder.parseResponse(HTTPBuilder.java:551)
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:480)
	... 10 more
```

**Comment by pmbohm** [comment]
Not reproducing the error on localhost using production gogoduck or localhost gogoduck.
Note the "queuePosition" = null returned from Gogoduck ??
`{"queuePosition":null,"status":"IN_PROGRESS","url":"https://gogoduck.aodn.org.au/gogoduck/job/bfc73d3d"}`
