### ISSUE TITLE
Out of space performing GoGoDuck aggregation

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2267]
### To Reproduce

Occurred in production for download of "IMOS - SRS Satellite - SST L3S - 06 day composite - day time" for time period 21/7/2000 to 21/7/2005

### What Happened

```
19 Aug 14:15:39 ERROR [worker.GoGoDuck] - Your aggregation failed! Reason for failure is: 'No space left on device'
au.org.emii.gogoduck.exception.GoGoDuckException: No space left on device
        at au.org.emii.gogoduck.worker.GoGoDuck.downloadFile(GoGoDuck.java:175)
        at au.org.emii.gogoduck.worker.GoGoDuck.downloadFiles(GoGoDuck.java:198)
        at au.org.emii.gogoduck.worker.GoGoDuck.run(GoGoDuck.java:101)
        at au.org.emii.wps.GoGoDuckProcess.execute(GoGoDuckProcess.java:80)
        at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:549)
        at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:51)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:201)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:169)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

### What should happen

Either the aggregation should succeed or the file limit should be decreased and an aggregation failed because too many files were requested to be downloaded error returned.

**Comment by bhasin85** [comment]
**Option 1**

_Decrease file limit_ :file_folder: 

**Option 2** 

_Increase disk space_ :floppy_disk: 

@pblain  Please advise. Thanks

**Comment by julian1** [comment]
FWIW, I sent an email to group responsible for developing HDF5, which is the protocol used to encode NetCDF v4, asking about streaming support.  This would allow us to write the aggregated output (of gogoduck and the netcdf generator) straight to the socket-descriptor without needing to cache the complete result server-side on a filesystem. Kind of important when all our data exists in a database or object storage.

A quick look through HDF5 api's through shows it's pretty file orientate, so I'm not very confident about the response.
