### ISSUE TITLE
Occasional errors finding config.ftl

### ISSUE THREAD

**Issue by jonescc** [aodn/aodn-portal#2333]
ERROR [freemarker.runtime] - Template processing error: "Error reading imported file config.ftl"
Error reading imported file config.ftl

The problematic instruction:

==> import "config.ftl" as my [on line 1, column 1 in content.ftl]

Java backtrace for programmers:

freemarker.template.TemplateException: Error reading imported file config.ftl
at freemarker.core.LibraryLoad.accept(LibraryLoad.java:122)
at freemarker.core.Environment.visit(Environment.java:221)
at
ERROR [geoserver.ows] - 
java.io.IOException: Error occured processing content template content.ftl for imos:soop_ba_trajectory_map
at org.geoserver.wms.featureinfo.HTMLFeatureInfoOutputFormat.write(HTMLFeatureInfoOutputFormat.java:138)
at org.geoserver.wms.featureinfo.GetFeatureInfoResponse.write(GetFeatureInfoResponse.java:109)
at org.geoserver.ows.Dispatcher.response(Dispatcher.java:996)
at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:279)
at org.springframework.web

**Comment by jonescc** [comment]
Perhaps due to chef run replacing this file at the time?

**Comment by jonescc** [comment]
Chef updates are atomic by default.  There have been no re-occurrences of this problem in the logs.  Closing for now.
