### ISSUE TITLE
Improve GeoServer WPS logging

### ISSUE THREAD

**Issue by bhasin85** [aodn/aodn-portal#2349]
WPS failed to log request/response xml (and other details like request uuid) for the following request

```
28 Sep 06:46:04 ERROR [wps.executor] - Process execution failed
org.geotools.process.ProcessException: java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483648
        at au.org.emii.wps.NetcdfOutputProcess.execute(NetcdfOutputProcess.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:549)
        at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:51)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:201)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:169)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483648
        at java.lang.String.charAt(String.java:658)
        at au.org.emii.ncdfgenerator.AttributeValueParser.peekChar(AttributeValueParser.java:21)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parseString(AttributeValueParser.java:213)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parseAttributeValue1(AttributeValueParser.java:138)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parseAttributes(AttributeValueParser.java:47)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parse(AttributeValueParser.java:29)
        at au.org.emii.ncdfgenerator.Variable.define(Variable.java:63)
        at au.org.emii.ncdfgenerator.NcdfEncoder.writeNext(NcdfEncoder.java:203)
        at au.org.emii.wps.NetcdfOutputProcess.execute(NetcdfOutputProcess.java:105)
        ... 12 more
28 Sep 06:46:04 INFO [geoserver.wps] - 
Request: execute
    service = WPS
    version = 1.0.0
    baseUrl = http://localhost:8081/geoserver/
    identifier:
        value = gs:NetcdfOutput
    dataInputs:
        input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@1ea5aac6 (value: typeName, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@e6ebce2input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@832a0d5 (value: cqlFilter, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@33dd0427input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@733bb70a (value: callbackParams, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@556e2ca0
    responseForm:
        rawDataOutput:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@3433e831 (value: result, codeSpace: null)
            mimeType = application/octet-stream
28 Sep 06:47:22 INFO [geoserver.wps] - 
Request: getServiceInfo
28 Sep 06:47:22 INFO [wps.NetcdfOutputProcess] - execute
28 Sep 06:47:24 ERROR [wps.executor] - Process execution failed
org.geotools.process.ProcessException: java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483648
        at au.org.emii.wps.NetcdfOutputProcess.execute(NetcdfOutputProcess.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:549)
        at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:51)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:201)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:169)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483648
        at java.lang.String.charAt(String.java:658)
        at au.org.emii.ncdfgenerator.AttributeValueParser.peekChar(AttributeValueParser.java:21)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parseString(AttributeValueParser.java:213)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parseAttributeValue1(AttributeValueParser.java:138)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parseAttributes(AttributeValueParser.java:47)
        at au.org.emii.ncdfgenerator.AttributeValueParser.parse(AttributeValueParser.java:29)
        at au.org.emii.ncdfgenerator.Variable.define(Variable.java:63)
        at au.org.emii.ncdfgenerator.NcdfEncoder.writeNext(NcdfEncoder.java:203)
        at au.org.emii.wps.NetcdfOutputProcess.execute(NetcdfOutputProcess.java:105)
        ... 12 more
28 Sep 06:47:24 INFO [geoserver.wps] - 
Request: execute
    service = WPS
    version = 1.0.0
    baseUrl = http://localhost:8081/geoserver/
    identifier:
        value = gs:NetcdfOutput
    dataInputs:
        input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@2f58f685 (value: typeName, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@79a0ae0binput[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@2402928f (value: cqlFilter, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@24e3fcc1input[0]:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@73e6f5d2 (value: callbackParams, codeSpace: null)
            data = net.opengis.wps10.impl.DataTypeImpl@4014e970
    responseForm:
        rawDataOutput:
            identifier = net.opengis.ows11.impl.CodeTypeImpl@1ce9d8ee (value: result, codeSpace: null)
            mimeType = application/octet-stream
'''

**Comment by jonescc** [comment]
Looks to me like these are the relevant artifact directory entries:

```
6684771    4 drwxr-xr-x   3 tomcat7  tomcat7      4096 Sep 28 16:46 ./d7707aa1-b16d-4a80-b238-19afddadb4ef
6684772    4 drwxr-xr-x   2 tomcat7  tomcat7      4096 Sep 28 16:46 ./d7707aa1-b16d-4a80-b238-19afddadb4ef/out
6684775    0 -rw-r--r--   1 tomcat7  tomcat7         0 Sep 28 16:46 ./d7707aa1-b16d-4a80-b238-19afddadb4ef/out/imos:soop_sst_nrt_trajectory_data.zip
```

and 

```
6684776    4 drwxr-xr-x   3 tomcat7  tomcat7      4096 Sep 28 16:47 ./1472189d-865e-42d9-abfb-7a66bbb09a3c
6684777    4 drwxr-xr-x   2 tomcat7  tomcat7      4096 Sep 28 16:47 ./1472189d-865e-42d9-abfb-7a66bbb09a3c/out
6684778    0 -rw-r--r--   1 tomcat7  tomcat7         0 Sep 28 16:47 ./1472189d-865e-42d9-abfb-7a66bbb09a3c/out/imos:soop_sst_nrt_trajectory_data.zip
```

Note the zero size for the output artifact and missing request.dat/response.xml files

So looks like the problem was with imos:soop_sst_nrt_trajectory_data

**Comment by jonescc** [comment]
Perhaps there's a race condition writing out the request/response/logging and encountering the error
