### ISSUE TITLE
Job failed but did not get email notification

### ISSUE THREAD

**Issue by kereid** [aodn/aodn-portal#2467]
In systest 

Steps to reproduce:

Add ANMN Temperature and salinity time-series as this is set up for netcdfoutput

Do not apply any subsets to get all data to download 

Proceed to step 3 and select download as netcdf

What should happen:

Either get all the data or it's too much and get email notification

What does happen:

Don't get an email and get this error on the status page

Process failed during execution java.lang.OutOfMemoryError: Java heap space Java heap space

**Comment by bhasin85** [comment]
**_Error Log_** https://service.au.sumologic.com/ui/index.html#section/search/FzGdE5ZPOXViihTja9tvMJMiilpbWZpB6t1frH4ej8o0UzrnOvWMuJIX5Qnwo3G9P96tQ7KYQrftCWZ2UnDcMeWQ8NrYvvymKtge47q76y3moyhVe9Hhh9xnZMbK1qVm

**Comment by jonescc** [comment]
Above log is for a production request I submitted using curl (incorrect format) - my bad.

The error reported above was caused by the netcdf generator running out of memory writing out a variable:

```
12 Apr 02:41:31 ERROR [wps.executor] - Process execution failed
org.geotools.process.ProcessException: java.lang.OutOfMemoryError: Java heap space
        at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:565)
        at org.geoserver.wps.executor.ProcessStartupFilter$ProcessStartupWrapper.execute(ProcessStartupFilter.java:51)
        at org.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:201)
        at e99adff2-8f08-4287-9478-764f8697a3eeorg.geoserver.wps.executor.DefaultProcessManager$ProcessCallable.call(DefaultProcessManager.java:169)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2219)
        at java.util.ArrayList.grow(ArrayList.java:242)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:216)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:208)
        at java.util.ArrayList.add(ArrayList.java:440)
        at au.org.emii.ncdfgenerator.Variable.addValueToBuffer(Variable.java:46)
        at au.org.emii.ncdfgenerator.NcdfEncoder.populateValues(NcdfEncoder.java:337)
        at au.org.emii.ncdfgenerator.NcdfEncoder.writeNext(NcdfEncoder.java:157)
        at au.org.emii.wps.NetcdfOutputProcess.execute(NetcdfOutputProcess.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:549)
        ... 7 more
```

The request was:  [request.txt](https://github.com/aodn/aodn-portal/files/918002/request.txt)

May actually just take more than the currently configured memory to do that subset.  Prod has 3GB configured Systest only 1GB.   I'd suggest upping the memory and retrying.

**Comment by jonescc** [comment]
Still should have sent an email in this situation - this exception may not being trapped appropriately.  Have raised https://github.com/aodn/geoserver-build/issues/222 to look at this.

**Comment by pblain** [comment]
Systest memory issue. Don't try to handle it.
